- .gitignore
- package-lock.json
- src/index.ts
- src/utils.ts
- test/lib.test.ts
- change `encodeBase64` to `encodeBase64Url `
> Fix encoding

- src/__tests__/__snapshots__/jws-verification-behavior.test.ts.snap
- src/__tests__/jws-verification-behavior.test.ts
- src/did.ts
Had to also change included DID documents.
> feat: Add disableTimecheck flag for verifyJWS

- .eslintrc.js
- .eslintrc.json
- .github/workflows/main.yml
- .prettierrc.json
- babel.config.js
- babel.config.json
- jest.config.json
- package.json
- prettier.config.js
- src/__tests__/jws-verification-behavior.test.ts
- src/__tests__/provider-behavior.test.ts
- src/__tests__/resolver-behavior.test.ts
- src/did.ts
- src/index.ts
- src/types.ts
- src/utils.ts
- tsconfig.build.json
- tsconfig.json
Apply ESM-transition checklist.
Divergence:
- have to add tsconfig.build.json to not include test files to NPM package.
> feat: Expose pure ESM

- package-lock.json
- package.json
- src/__tests__/provider-behavior.test.ts
- src/did.ts
Adds verification of optional `capability` CACAO OCAP in `verifyJWS`
Added a new test under `provider-behavior.test.ts` which tests verifying a JWS with a capability attached.
> add cacao verification to verifyJWS

- package-lock.json
- package.json
> feat: Dual-publish

- package-lock.json
- package.json
- src/__tests__/provider-behavior.test.ts
Updates to the latest version of CACAO, includes some undefined property checking when converting from SIWE to CACAO
Tests were modified to work with patch
> bump cacao to 0.0.16

- src/__tests__/jws-verification-behavior.test.ts
- src/did.ts
When does https://ceramicnetwork.github.io/js-did/interfaces/verifyjwsoptions.html get updated? 
Added tests to `jws-verification-behavior.test`
> feat: add revocationPhaseOut option to verifyJWS

- package-lock.json
- package.json
- src/did.ts
passes option, tested in cacao package 
ref - https://github.com/ceramicnetwork/cacao/pull/10
> feat: add cacao phaseout option support

- README.md
Provides a first draft for documentation and some security implications around having a grace period for key revocation. 
N/A
> [NET-1304] Security implications and documentation around key revocation grace period

- website/docusaurus.config.js
Describe the tests that you ran to verify your changes. Provide instructions for reproduction.
> Added algolia doc search to the website

- packages/did-session/package.json
Bumped the version after fixing links to repo in 7f6003d97349812ceb75b5302302998bbcb1e607
> Patch version release did-session@0.1.2

- docs/modules/did_session.md
- packages/did-session/README.md
- packages/did-session/src/index.ts
- packages/pkh-ethereum/src/authmethod.ts
add docs warning (v1 did-sessions)
docs fix 
web auth eth fix
> fix: eth web auth, docs, warning for version

- website/docusaurus.config.js
> Add Google tag

- docs/modules/did_session.md
- docs/modules/pkh_ethereum.md
- docs/modules/pkh_solana.md
- packages/did-session/README.md
- packages/did-session/src/index.ts
- packages/pkh-ethereum/README.md
- packages/pkh-ethereum/src/index.ts
- packages/pkh-solana/README.md
- packages/pkh-solana/src/index.ts
- website/docs/api/modules/did_session.md
- website/docs/api/modules/key_did_resolver.md
- website/docs/api/modules/pkh_ethereum.md
- website/docs/api/modules/pkh_solana.md
- website/docs/authorization.md
- website/docs/configuration.md
- website/docs/guides/upgrading-did-session.md
- website/docs/guides/using-with-composedb-client.md
- website/docs/managing-sessions.md
Fixed typos in pkh_ethereum docs around getting ethereum addresses and auth method for didsession
> Fixed typos in pkh_ethereum docs

- docs/classes/key_did_provider_secp256k1.Secp256k1Provider.md
- docs/index.md
- docs/modules/key_did_provider_secp256k1.md
- packages/key-did-provider-secp256k1/.eslintrc.json
- packages/key-did-provider-secp256k1/.gitignore
- packages/key-did-provider-secp256k1/LICENSE-APACHE
- packages/key-did-provider-secp256k1/LICENSE-MIT
- packages/key-did-provider-secp256k1/README.md
- packages/key-did-provider-secp256k1/jest.config.json
- packages/key-did-provider-secp256k1/package.json
- packages/key-did-provider-secp256k1/src/index.ts
- packages/key-did-provider-secp256k1/test/__snapshots__/index.test.ts.snap
- packages/key-did-provider-secp256k1/test/index.test.ts
- packages/key-did-provider-secp256k1/tsconfig.json
- packages/key-did-provider-secp256k1/tsconfig.lint.json
- pnpm-lock.yaml
- tsconfig.docs.json
- tsconfig.json
Moves https://github.com/ceramicnetwork/key-did-provider-secp256k1, but that package was a bit out of date, this mostly copies over everything from `key-did-provider-ed25519` for `secp256k1` instead
> feat: add key did provider secp256k1 package

- packages/key-did-provider-secp256k1/README.md
- packages/key-did-provider-secp256k1/package.json
- packages/key-did-provider-secp256k1/src/index.ts
- packages/key-did-provider-secp256k1/test/__snapshots__/index.test.ts.snap
- packages/key-did-provider-secp256k1/test/index.test.ts
Changes package name to @didtools/key-secp256k1 and released.
> build: change package name, secp25k1 provider

- packages/pkh-tezos/README.md
- packages/pkh-tezos/package.json
- packages/pkh-tezos/src/verifier.ts
- packages/pkh-tezos/test/index.test.ts
- pnpm-lock.yaml
> feat(pkh-tezos): remove @taquito/utils for stablelib

- docs/classes/didtools_multidid.Multidid.md
- docs/index.md
- docs/modules/didtools_multidid.md
- packages/multidid/.eslintrc.json
- packages/multidid/.gitignore
- packages/multidid/LICENSE-APACHE
- packages/multidid/LICENSE-MIT
- packages/multidid/README.md
- packages/multidid/jest.config.json
- packages/multidid/package.json
- packages/multidid/src/index.ts
- packages/multidid/test/index.test.ts
- packages/multidid/tsconfig.json
- packages/multidid/tsconfig.lint.json
- pnpm-lock.yaml
- tsconfig.docs.json
- tsconfig.json
Add multidid library based on [specification](https://github.com/ChainAgnostic/multidid) and examples as test vectors. 
Does not have did:pkh support yet, and few small todos left. 
Pretty simple, but feedback on interface, what to add/remove etc, would be helpful.
> feat: add multidid library with did:* and did:key support

- .changeset/brown-peaches-wait.md
- .changeset/rich-steaks-behave.md
- packages/dids/package.json
- packages/dids/test/provider-behavior.test.ts
- packages/key-did-provider-ed25519/package.json
- packages/pkh-ethereum/package.json
- packages/pkh-ethereum/src/authmethod.ts
- packages/pkh-ethereum/src/verifier.ts
- packages/pkh-ethereum/test/index.test.ts
- pnpm-lock.yaml
Started as "We need to release key-did-provider-ed25519", ended with "Oh, no ethers behemoth please".
And yes, finally added changesets, so that I can release the provider.
> chore: Do not use ethers in prod for a minor thing

- packages/did-session/package.json
- pnpm-lock.yaml
> did-session@2.1.0

- README.md
A followup for https://github.com/ceramicnetwork/js-ceramic/pull/3208 adding more of the packages to the monorepo README.
> chore: Update list of packages on README
