- README.md
- package.json
- src/index.ts
- src/utils.ts
- test/lib.test.ts
Updates the `createDagJWS` method so that it plays nicer with ipfs. You can now put the encoded block of the payload directly into the ipfs blockstore (see readme for an example).
> ref: refined createDagJWS api and added documentation

- CHANGELOG.md
- package.json
- src/index.ts
- test/lib.test.ts
Conveniently get the payload when you verify a JWS.
> feat: return payload in verifyJWS method

- src/__tests__/__snapshots__/jws-verification-behavior.test.ts.snap
- src/__tests__/jws-verification-behavior.test.ts
- src/did.ts
- src/utils.ts
If `did-A` is the controller of `did-B` a signature performed by A should be seen as valid if B is the issuer. We use the controller property in DID documents to allow for Safe and NFT DIDs.
> feat: Pass issuer to verifyJWS

- jest.config.json
- package-lock.json
- package.json
- src/__tests__/provider-behavior.test.ts
- src/did.ts
- src/types.ts
Update `cids` --> `multiformats/cid`
Update `dag-jose-utils` to latest
`CID.asCID()` is used to convert from different versions of `multiformats/cid`
`ipfs-core` currently used in `js-ceramic` and `ceramic-anchor-service` uses `cids` but `ipfs-core` will be updated shortly to the latest version in these packages which uses `multiformats/cid`
Unit tests still pass
Manual IPFS tests have been done
Note: Older versions of the `ipfs-core` package can still be used. You just have to convert the did CIDS into IPFS cids before using IPFS. 
> chore: update cids and dag-jose-utils

- package-lock.json
- package.json
Product team pointed out that `dids` had a deep dependency on `fs` and `path` due to using `apg` during ABNF parsing. Cacao new version was released which fixed that issue. This version bump updates `dids` to use the latest version of CACAO so it is browser compatible.
> bump cacao version

- package.json
- src/did.ts
Prior to this PR, there existed a nested conditional. If code entered the parent conditional but not the child, there was no else statement to throw an error. This resulted in invalid JWS's being able to be verified, as discovered during CACAO's integration tests. 
This PR fixes that by merging both conditionals into one, so the `else` points to the pre-existing error throw.
Describe the tests that you ran to verify your changes. Provide instructions for reproduction.
> fix conditional so it cannot return without an error

- package-lock.json
- package.json
Cacao commit https://github.com/ceramicnetwork/cacao/commit/866872b913dba4a20ff8c02a1ebd3b3a1127af92 updated the cacao data structure to separate the header and signature types. This version bump is to use that version in js-did.
Tests did not change.
> Bump cacao version to 0.0.14

- package-lock.json
- package.json
- src/__tests__/jws-verification-behavior.test.ts
- src/__tests__/provider-behavior.test.ts
- src/did.ts
- src/utils.ts
title
Previous tests were modified to conform
> [NET-1253] use `Date` instead of `number` for `atTime`

- .github/workflows/main.yml
- .gitignore
- package-lock.json
- package.json
Mostly meant to avoid regressions affecting consuming packages when built-in node modules are used in dependencies.
Updated CI pipeline.
> Add webpack to the CI pipeline to ensure browser support

- package-lock.json
- package.json
Update versions of the dependencies
Apparently, we do not use `query-string` package anymore. And `ethers` is only dev dependency. Adjusted `package.json` accordingly.
> chore: Update packages

- src/__tests__/provider-behavior.test.ts
- src/did.ts
createJWS and createDagJWS throw when creating with expired cacao now 
could add other validation after, only for expiration for now
> feat: throw on expired cacao on creation, not only validation

- website/docs/installation.mdx
- website/docs/introduction.md
- website/docusaurus.config.js
- website/src/pages/index.tsx
We want the docs to be available ad did.js.org and in general we want to use the 'did' name and in general 'DIDs' seem confusing. I replaced it with just 'js-did' for now. We'll gather more feedback to see, if we want to change this name to something else.
Describe the tests that you ran to verify your changes. Provide instructions for reproduction.
> Don't use 'DIDs' as an umbrella name covering packages in

- packages/did-session/package.json
- packages/dids/package.json
- packages/dids/src/did.ts
- packages/dids/test/provider-behavior.test.ts
- pnpm-lock.yaml
If `disableTimecheck` is passed to `verifyJWS`, corresponding flag is set to cacao verification function.
Note:
- Apparently, `did-session` uses `ceramic-cacao` package just for types. Moved it to `devDependencies`.
> feat: Allow expired capabilities through flag

- packages/did-session/package.json
The old links lead to non-existent pages
> Update broken links to the repo

- packages/pkh-ethereum/src/authmethod.ts
- packages/pkh-solana/src/authmethod.ts
This PR increases the default cacao expiry when used with authmethods in did-session from 1 day to 7 days. We still have the 1 day revocation phaseout, effectively making it 8 days. Expiry is just a client default, not in the cacao library or enforced in anyways, clients may already configure their own but expect most rely on default. Default phaseout is more likely be recognized, as few would change that config value. 
We can discuss the time interval we want to use here. Also how we want to version the release.
> feat: increase default cacao expiry to one week (from 1 day)

- packages/pkh-ethereum/src/authmethod.ts
- packages/pkh-ethereum/src/utils.ts
Checksum (mixed case) addresses in eth auth where no longer normalized in switch to did-session. The effect is more minimal here than for caip10 links, and less likely to come up, as it would require the same account to use to two different wallets/providers, which is unlikely (two returning diff format addresses, same wallets either case would not throw an error). It would/will be more problematic for general queries/relations. 
This adds normalization for eth address and is technically a breaking change, and existing checksum address providers that did work fine, will now break, no longer allow content to be added to those streams. It should be few to none returning this, but should try to capture before merging (PR in draft for now)
> fix: normalize checksum address eth

- packages/pkh-ethereum/package.json
- packages/pkh-ethereum/src/authmethod.ts
- pnpm-lock.yaml
personal_sign spec expects a hex encoded utf8 message, most providers do seem to support both hex & utf8 strings (ie metamask provider and we havent had any other reported errors from common providers), plus most libraries (ethers, web3) accept both and encode as hex before making provider call 
this will provide better general support, esp any other providers that may just follow spec 
This will resolve issue - https://github.com/ceramicnetwork/js-did/issues/131
> fix: eth personal sign hex message

- packages/did-session/package.json
- packages/dids/package.json
- packages/key-did-provider-ed25519/package.json
- packages/key-did-provider-secp256k1/package.json
- packages/key-did-provider-secp256k1/src/index.ts
- packages/key-did-provider-secp256k1/test/index.test.ts
- packages/pkh-solana/package.json
- packages/pkh-solana/src/verifier.ts
- packages/pkh-tezos/package.json
- packages/pkh-tezos/src/verifier.ts
- pnpm-lock.yaml
`@stablelib/random` is to remain. `@stablelib/ed25519` is to remain till https://github.com/paulmillr/noble-curves/pull/32 is released. Otherwise, moved to noble-crypto.
> chore: Bump to the latest did-jwt and replace some stablelib with noble-crypto

- .github/workflows/build-docs.yml
- .github/workflows/build-test.yml
- .github/workflows/deploy-docs.yml
- package.json
- packages/cacao/package.json
- packages/did-session/package.json
- packages/dids/package.json
- packages/integration/package.json
- packages/jest-environment-ceramic/package.json
- packages/key-did-provider-ed25519/package.json
- packages/key-did-provider-secp256k1/package.json
- packages/key-did-resolver/package.json
- packages/pkh-did-resolver/package.json
- packages/pkh-ethereum/package.json
- packages/pkh-solana/package.json
- packages/pkh-stacks/package.json
- packages/pkh-tezos/package.json
- pnpm-lock.yaml
- website/docs/api/classes/didtools_key_secp256k1.Secp256k1Provider.md
- website/docs/api/classes/key_did_provider_ed25519.Ed25519Provider.md
- website/docs/api/index.md
- website/docs/api/modules/pkh_ethereum.md
- website/docs/api/modules/pkh_tezos.md
- website/package.json
Main changes to the CI setup are dropping Node v14 and testing for v16, v18 and v20, as well as using pnpm v8.
> Bump dependencies and update CI setup

- packages/did-session/package.json
- packages/did-session/setup.jest.js
- packages/did-session/src/index.ts
- packages/did-session/src/sessionStore.ts
- packages/did-session/test/lib.test.ts
- pnpm-lock.yaml
This PR adds support for sessions that are persisted. These sessions are created and loaded using `DIDSession.get(...)`. The sessions use the new `@didtools/key-webcrypto` did provider where keys are stored securely in the browser (outside of DOM). These keys along with the Cacao are persisted using IndexedDB.
Currently only browsers are supported. The `.get` function will throw an error if called in nodejs.
One new unit test where added that uses `fake-indexeddb` and jsdom jest env.
> Add support for persisted sessions

- packages/key-webauthn/README.md
Last minute commit that didn't make it into: [PR-175](https://github.com/ceramicnetwork/js-did/pull/175)
Changes done to `README.md`:
- Sorted samples by Operative System
- Added Android 10 / OS-Authenticator results for Firefox & Chrome
https://github.com/ceramicnetwork/js-did/pull/175
> Sorted rows by OS; Added samples for Android10/OS-Authenticator

- packages/cacao/CHANGELOG.md
- packages/cacao/package.json
- packages/codecs/CHANGELOG.md
- packages/codecs/package.json
- packages/did-session/CHANGELOG.md
- packages/did-session/package.json
- packages/dids/CHANGELOG.md
- packages/dids/package.json
- packages/key-did-provider-ed25519/CHANGELOG.md
- packages/key-did-provider-ed25519/package.json
- packages/key-did-provider-secp256k1/CHANGELOG.md
- packages/key-did-provider-secp256k1/package.json
- packages/key-webauthn/CHANGELOG.md
- packages/key-webauthn/package.json
- packages/pkh-did-resolver/package.json
Version bump for codecs so it can release. Fix repository in pkh-did-resolver so that it can be publishshed.
codecs@3.0.0
> chore: multifomats 13 for codecs

- packages/dids/src/did.ts
- packages/dids/test/provider-behavior.test.ts
There was a bug introduced in #176 where CACAO/SIWE message signed with eip55 encoding would result in an  `unsupportedDidMethod` error. This was because an equality check would fail due to the difference between a lower case and a mixed case (eip55) ethereum address. This PR fixes this problem.
> fix(dids): Verify eip55 formatted CACAOs correctly

- packages/did-session/CHANGELOG.md
- packages/did-session/package.json
- packages/dids/CHANGELOG.md
- packages/dids/package.json
- packages/key-did-provider-ed25519/CHANGELOG.md
- packages/key-did-provider-ed25519/package.json
- packages/key-did-provider-secp256k1/CHANGELOG.md
- packages/key-did-provider-secp256k1/package.json
Release new patch version of dids with #184
> chore: release dids@5.0.1, did-session@3.0.2, key-did-provider-ed25519@4.0.2, @didtools/key-secp256k1@0.3.2

- packages/did-session/package.json
- packages/did-session/test/lib.test.ts
- packages/jest-environment-ceramic/package.json
- packages/pkh-ethereum/src/authmethod.ts
- pnpm-lock.yaml
A while back we updated the `@didtools/cacao` package to be able to verify SIWE messages with both eip55 encoded ethereum addresses as well as lower case ones. This is because the SIWE spec requires the address to be eip55. We needed to roll this change out to `@ceramicnetwork/*` packages before we could change the default behavior to sign eip55 messages from the pkh-ethereum package. This PR makes this change.
> fix: make SIWE default to EIP55
